insert into compte (numero,libelle) values
(10,'Capital'),
(101,'Reserves'),
(12,'Resultat'),
(16,'Emprunts'),
(20,'Immobilisations incorporelles'),
(21,'Innobilisations corporelles'),
(3,'Stock'),
(40,'Fournisseurs'),
(41,'Clients'),
(42,'Personnels'),
(43,'Organismes sociaux'),
(44,'Etat'),
(4456,'TVA deductible'),
(4457,'TVA collecte'),
(4458,'TVA a verser'),
(45,'Compte des associes'),
(46,'Debiteurs et crediteurs divers'),
(51,'Banque'),
(53,'Caisse'),
(60,'Achat de bien consommables'),
(61,'Achat de services'),
(63,'Impot et taxes'),
(641,'Salaire du aux personnels'),
(645,'Charge patronnale'),
(65,'Autres charges de gestion courantes'),
(66,'Charges financieres'),
(67,'Charges extraordinaires'),
(68,'dotation aux amortissements'),
(69,'Impots sur les resultats'),
(70,'Vente de biens consommables'),
(74,'Subvention de l etat'),
(75,'Autres produits de gestion courante'),
(76,'Produits financiers'),
(77,'Produits extraordinaires'),
(78,'Reprise sur amortissements et provisions');

